version: '3.8'

services:
  google-mcp:
    build:
      context: ./services/google-mcp
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - PORT=3010
    env_file:
      - ./services/google-mcp/.env
    networks:
      - rendetalje-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3010/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  inbox-orchestrator:
    build:
      context: ../../services/tekup-ai/packages/inbox-orchestrator
      dockerfile: Dockerfile
    ports:
      - "3011:3011"
    environment:
      - NODE_ENV=production
      - PORT=3011
      - GOOGLE_MCP_URL=http://google-mcp:3010
      - TEKUP_BILLY_URL=http://tekup-billy:3012
      - GEMINI_API_KEY=AIzaSyAQqh1Ow6UZ_Xv6OyDKcPNYUTbW35I_roQ
    networks:
      - rendetalje-network
    depends_on:
      google-mcp:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3011/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tekup-cloud-dashboard:
    build:
      context: ../../apps/web/tekup-cloud-dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://localhost:3000
      - VITE_GOOGLE_MCP_URL=http://localhost:3010
      - VITE_ORCHESTRATOR_URL=http://localhost:3011
      - VITE_DISABLE_WS=true
    networks:
      - rendetalje-network
    depends_on:
      - google-mcp
      - inbox-orchestrator
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/dashboard', (res) => { process.exit([200, 304, 404].includes(res.statusCode) ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  rendetalje-network:
    driver: bridge

volumes:
  google-mcp-data:
  orchestrator-data: