# Simplified Docker Compose for TekUp Job Scheduling System
# Minimal setup for testing the application container

version: '3.8'

services:
  # TekUp CRM Web Application - Job Scheduling System
  tekup-crm-web:
    build: 
      context: .
      dockerfile: apps/tekup-crm-web/Dockerfile
    container_name: tekup-job-scheduling
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s