# Docker Compose override for active development
# Focus on website and lead platform with essential services

services:
  # Databases - keep running for data persistence
  postgres:
    profiles: ["development", "full"]
  
  redis:
    profiles: ["development", "full"]

  # Website - Marketing site with Tailwind CSS 4.1
  website:
    profiles: ["development", "full"]
    build:
      context: ./apps/website
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/website:/app
      - website_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_LEAD_PLATFORM_URL=http://localhost:3003
      - PORT=8081
      - HMR_HOST=localhost
    ports:
      - "8081:8081"
    command: pnpm dev --host *******
    stdin_open: true
    tty: true
    networks:
      - tekup-dev

  # Lead Platform Frontend - React app for lead management
  tekup-lead-platform-web:
    profiles: ["development", "full"]
    build:
      context: ./apps/tekup-lead-platform-web
      dockerfile: ../website/Dockerfile.dev  # Reuse website dockerfile structure
    volumes:
      - ./apps/tekup-lead-platform-web:/app
      - lead_platform_web_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:3003
      - PORT=3002
      - HMR_HOST=localhost
    ports:
      - "3002:3002"
    command: pnpm dev --host 0.0.0.0
    stdin_open: true
    tty: true
    networks:
      - tekup-dev

  # MCP Browser Tools - For AI automation and testing
  mcp-browser:
    profiles: ["development", "full"]
    image: node:20-slim
    container_name: tekup-mcp-browser-dev
    working_dir: /app
    volumes:
      - ./.mcp:/app
    environment:
      - NODE_ENV=development
      - BROWSER_WS_URL=ws://localhost:9009
      - MCP_SERVER_PORT=9010
    ports:
      - "9010:9010"  # MCP server port
      - "9009:9009"  # WebSocket port for browser control
    command: bash -c "npm install -g @agent-infra/mcp-server-browser && mcp-server-browser"
    networks:
      - tekup-dev

  # Development tools
  pgadmin:
    profiles: ["development", "full"]

  redis-commander:
    profiles: ["development", "full"]

volumes:
  website_node_modules:
  lead_platform_web_node_modules:

networks:
  tekup-dev:
    external: true
    name: tekup-development-network