packages:
  - 'apps/*'
  - 'packages/*'
  - "libs/*"
  # Strategic Initiative Applications
  - 'apps/mcp-studio-enterprise'
  - 'apps/danish-enterprise'  
  - 'apps/rendetalje-os'
  - 'apps/foodtruck-os'
  - 'apps/essenza-pro'
