# Render.com Blueprint for RendetaljeOS
# This file defines all services needed for production deployment

services:
  # Backend API Service
  - type: web
    name: rendetalje-backend
    env: node
    region: frankfurt
    plan: standard
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: rendetalje-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: rendetalje-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: BILLY_API_KEY
        sync: false
      - key: TEKUP_VAULT_API_KEY
        sync: false
      - key: AI_FRIDAY_API_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
    domains:
      - api.rendetalje.dk

  # Frontend Owner Portal
  - type: web
    name: rendetalje-frontend-owner
    env: static
    region: frankfurt
    buildCommand: cd frontend && npm ci && npm run build:owner
    staticPublishPath: frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://api.rendetalje.dk
      - key: NEXT_PUBLIC_WS_URL
        value: wss://api.rendetalje.dk
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false
      - key: NEXT_PUBLIC_GA_TRACKING_ID
        sync: false
    domains:
      - portal.rendetalje.dk

  # Frontend Customer Portal
  - type: web
    name: rendetalje-frontend-customer
    env: static
    region: frankfurt
    buildCommand: cd frontend && npm ci && npm run build:customer
    staticPublishPath: frontend/out
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://api.rendetalje.dk
      - key: NEXT_PUBLIC_WS_URL
        value: wss://api.rendetalje.dk
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false
    domains:
      - kunde.rendetalje.dk

  # Redis Cache Service
  - type: redis
    name: rendetalje-redis
    region: frankfurt
    plan: starter
    maxmemoryPolicy: allkeys-lru

databases:
  # PostgreSQL Database (External - Supabase)
  # Configuration handled through environment variables

# Background Jobs (Optional - can be added later)
# - type: background
#   name: rendetalje-jobs
#   env: node
#   buildCommand: cd backend && npm ci && npm run build
#   startCommand: cd backend && npm run start:jobs
#   envVars:
#     # Same as backend service

# Monitoring and Health Checks
healthChecks:
  - path: /health
    intervalSeconds: 30
    timeoutSeconds: 10
    unhealthyThresholdCount: 3
    healthyThresholdCount: 2

# Auto-deploy configuration
autoDeploy:
  branch: main
  buildFilter:
    paths:
      - backend/**
      - frontend/**
      - deployment/**

# Notifications
notifications:
  - type: email
    emails:
      - devops@rendetalje.dk
    events:
      - deploy-started
      - deploy-succeeded
      - deploy-failed
      - service-suspended

# Custom headers for security
headers:
  - path: /*
    headers:
      X-Frame-Options: DENY
      X-Content-Type-Options: nosniff
      X-XSS-Protection: 1; mode=block
      Strict-Transport-Security: max-age=31536000; includeSubDomains
      Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.google.com *.googleapis.com; style-src 'self' 'unsafe-inline' *.googleapis.com; img-src 'self' data: https:; font-src 'self' *.googleapis.com *.gstatic.com; connect-src 'self' *.supabase.co wss://*.supabase.co https://api.rendetalje.dk wss://api.rendetalje.dk

# Redirects
redirects:
  - source: /
    destination: /dashboard
    type: 301
  - source: /app
    destination: https://portal.rendetalje.dk
    type: 301