version: '3.9'
services:
  tekup-crm-web:
    build: .
    image: tekup-crm-web:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - tekup-crm-web
