version: '3.9'
services:
  tekup-crm-web:
    build: .
    image: tekup-crm-web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    depends_on: []
