version: '3.8'

services:
  tekup-gmail-automation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tekup-gmail-automation
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    networks:
      - tekup-network

  redis:
    image: redis:7-alpine
    container_name: tekup-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - tekup-network

  postgres:
    image: postgres:15-alpine
    container_name: tekup-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=tekup_gmail
      - POSTGRES_USER=tekup
      - POSTGRES_PASSWORD=tekup_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tekup-network

  nginx:
    image: nginx:alpine
    container_name: tekup-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - tekup-gmail-automation
    networks:
      - tekup-network

volumes:
  redis_data:
  postgres_data:

networks:
  tekup-network:
    driver: bridge
