site_name: TekUp AI Assistant
site_description: Local AI Assistant for automating daily business tasks
site_author: TekUp Team
site_url: https://github.com/JonasAbde/tekup-ai-assistant

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

nav:
  - Home: index.md
  - Getting Started:
    - Installation: SETUP.md
    - Architecture: ARCHITECTURE.md
    - Status Report: AI_ASSISTANT_STATUS_REPORT.md
    - Installed Models: INSTALLED_MODELS_REPORT.md
    - Qwen Test Results: QWEN_TEST_RESULTS.md
    - Changelog: CHANGELOG.md
  - Documentation:
    - Daily Workflows: WORKFLOWS.md
    - Troubleshooting: TROUBLESHOOTING.md
    - MCP Web Scraper: MCP_WEB_SCRAPER_GUIDE.md
    - MCP Resources: MCP_RESOURCES.md
    - TekUp Code Standards: TEKUP_UNIFIED_CODE_STANDARDS.md
  - Billy Integration:
    - Integration Summary: BILLY_INTEGRATION_SUMMARY.md
    - Complete Report: BILLY_INTEGRATION_COMPLETE.md
    - Code Analysis: analysis/TEKUP_BILLY_COMPLETE_ANALYSIS.md
    - Repository Inventory: analysis/REPO_INVENTORY.md
  - API Reference:
    - Billy.dk API: api/tekup-billy-api.md
  - Guides:
    - Daily Workflow Guide: guides/daily-workflow.md
    - CLI Control Guide: guides/cli-control.md
    - Billy.dk Integration: guides/billy-integration.md
    - Docker Troubleshooting: guides/docker-troubleshooting.md
    - TekupVault Guide: guides/tekupvault-guide.md
  - Examples:
    - Invoice Creation: examples/create-invoice.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - tables
  - admonition
  - toc:
      permalink: true
      toc_depth: "1-3"

repo_url: https://github.com/JonasAbde/tekup-ai-assistant
repo_name: tekup-ai-assistant
edit_uri: edit/master/
