global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  # PostgreSQL Database Monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'tekup-postgres-primary'

  # Redis Monitoring  
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Application metrics (hvis apps eksponerer metrics)
  - job_name: 'flow-api'
    static_configs:
      - targets: ['localhost:4000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'crm-api'
    static_configs:
      - targets: ['localhost:4001']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # TekUp Flow API
  - job_name: 'tekup-flow-api'
    static_configs:
      - targets: ['localhost:4000']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # TekUp CRM API  
  - job_name: 'tekup-crm-api'
    static_configs:
      - targets: ['localhost:4001']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # TekUp Secure Platform
  - job_name: 'tekup-secure-platform'
    static_configs:
      - targets: ['localhost:4002']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node.js Process Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']

  # PostgreSQL Metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
